// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIEG_API.Models
{
    public partial class Bank
    {
        public int BankId { get; set; }
        public int Code { get; set; }
        public string Name { get; set; }
    }
}