// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIEG_API.Models
{
    public partial class ForumArticle
    {
        public int ForunArticleId { get; set; }
        public int MemberId { get; set; }
        public string Category { get; set; }
        public int ProductId { get; set; }
        public string Title { get; set; }
        public string ArticleContent { get; set; }
        public int LikeCount { get; set; }
        public int ViewsCount { get; set; }
        public DateTime AddTime { get; set; }
        public string Img { get; set; }
        public bool? ValIdity { get; set; }
        public int ProductCategoryId { get; set; }
    }
}