// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIEG_API.Models
{
    public partial class MemberCoupons
    {
        public int MemberCouponsId { get; set; }
        public int CouponsId { get; set; }
        public int MemberId { get; set; }
        public int Count { get; set; }
    }
}