// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIEG_API.Models
{
    public partial class News
    {
        public int NewsId { get; set; }
        public string Img { get; set; }
        public string Title { get; set; }
        public string NewsContent { get; set; }
        public DateTime ReleaseTime { get; set; }
        public bool? ValIdity { get; set; }
        public int NewsCategory { get; set; }
        public DateTime AddTime { get; set; }
        public int ViewsCount { get; set; }
    }
}