// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIEG_API.Models
{
    public partial class Product
    {
        public int ProductId { get; set; }
        public int ProductCategoryId { get; set; }
        public string Name { get; set; }
        public DateTime AddTime { get; set; }
        public bool? ValIdity { get; set; }
        public int Price { get; set; }
        public string Size { get; set; }
        public string ImgFront { get; set; }
        public string ImgBack { get; set; }
        public string ImgSide { get; set; }
        public int? ViewsCount { get; set; }
    }
}